version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local
    environment:
      - BACKEND_URL=http://backend:8080
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env/.dev_env